language: ruby
rvm:
  - 2.2.0
before_script:
  - cp config/database.yml.travis config/database.yml
  - bundle exec rake db:create
  - bundle exec rake db:migrate
script:
  - bundle exec rake spec

  before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
